name: chDB-go

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Fetch library
      run: |
          sudo wget https://github.com/metrico/libchdb/releases/latest/download/libchdb.zip
          sudo unzip libchdb.zip
          sudo mv libchdb.so /usr/lib/libchdb.so
          sudo ldconfig
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.18
    - name: Build
      run: |
          go mod tidy
          go build -o chdbgo main.go
    - name: Test
      run: ./chdbgo

