name: chDB-go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: "3.7"
    - name: Fetch library
      run: |
          sudo apt update && sudo apt install -y binutils
          python3 -m pip install chdb
          find /opt/hostedtoolcache/Python -name _chdb*.so
          sudo mv /opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/chdb/_chdb.cpython-37m-x86_64-linux-gnu.so /usr/lib/libchdb.so
          sudo strip /usr/lib/libchdb.so
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20

    - name: Build
      run: |
          sudo mv chdb /opt/hostedtoolcache/go/1.2.2/x64/src/pkg/chdb
          go build -o chdbgo main.go

    - name: Test
      run: ./chdbgo
