name: chDB-go Release

on:
  release:
    types: [created]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: "3.7"
    - name: Fetch library
      run: |
          sudo apt update && sudo apt install -y binutils
          python3 -m pip install chdb
          find /opt/hostedtoolcache/Python -name _chdb*.so
          sudo mv /opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/chdb/_chdb.cpython-37m-x86_64-linux-gnu.so /usr/lib/libchdb.so
          sudo strip /usr/lib/libchdb.so
          sudo zip /tmp/libchdb.x86_64-linux-gnu.zip /usr/lib/libchdb.so
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.18
    - name: Build
      run: |
          go mod tidy
          go build -o chdbgo main.go        
    - name: Get Version
      run: |
        echo "VERSION=${{  github.ref_name }}" >> $GITHUB_ENV
    - name: Upload release
      if: github.event_name != 'pull_request'
      uses: boxpositron/upload-multiple-releases@1.0.7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_config: |
            chdbgo
            /tmp/libchdb.x86_64-linux-gnu.zip
        tag_name: ${{ env.VERSION }}
        release_name: chdbgo_${{ env.VERSION }}
        draft: false
        prerelease: false
        overwrite: true   
