name: chDB-go Release

on:
  release:
    types: [created]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Fetch library
      run: |
          sudo apt update && sudo apt install -y binutils
          sudo wget https://github.com/metrico/libchdb/releases/download/0.7.0/libchdb_amd64.zip
          sudo unzip libchdb_amd64.zip
          sudo mv libchdb.so /usr/lib/libchdb.so
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.18
    - name: Build
      run: |
          go mod tidy
          go build -o chdbgo main.go        
    - name: Get Version
      run: |
        echo "VERSION=${{  github.ref_name }}" >> $GITHUB_ENV
    - name: Upload release
      if: github.event_name != 'pull_request'
      uses: boxpositron/upload-multiple-releases@1.0.7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_config: |
            chdbgo
            libchdb_amd64.zip
        tag_name: ${{ env.VERSION }}
        release_name: chdbgo_${{ env.VERSION }}
        draft: false
        prerelease: false
        overwrite: true   
